//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetHistory.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetHistory.Core.Resources.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username has not been inputted!.
        /// </summary>
        public static string EmptyUserName {
            get {
                return ResourceManager.GetString("EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой валюты нет в списке доступных валют.
        /// </summary>
        public static string InvalidCurrencyType {
            get {
                return ResourceManager.GetString("InvalidCurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:
        ///Password is too long..
        /// </summary>
        public static string LongPassword {
            get {
                return ResourceManager.GetString("LongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance value can&apos;t be negative..
        /// </summary>
        public static string NegativeBalanceError {
            get {
                return ResourceManager.GetString("NegativeBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note has not been created..
        /// </summary>
        public static string NoteCreationError {
            get {
                return ResourceManager.GetString("NoteCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (ID : {0}) does not exist.
        /// </summary>
        public static string NoteDoesNotExist {
            get {
                return ResourceManager.GetString("NoteDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no notes to be updated..
        /// </summary>
        public static string NotesToUpdateListIsEmpty {
            get {
                return ResourceManager.GetString("NotesToUpdateListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (id : {0})
        ///has been created successfully!.
        /// </summary>
        public static string NoteSuccessfullyCreated {
            get {
                return ResourceManager.GetString("NoteSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (id : {0})
        ///has been updated successfully!.
        /// </summary>
        public static string NoteSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("NoteSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles are not set..
        /// </summary>
        public static string RolesAreNotSet {
            get {
                return ResourceManager.GetString("RolesAreNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room has not been created..
        /// </summary>
        public static string RoomCreationError {
            get {
                return ResourceManager.GetString("RoomCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Id: {0}.
        ///Room does not exist..
        /// </summary>
        public static string RoomDoesNotExist {
            get {
                return ResourceManager.GetString("RoomDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room (id : {0})
        ///has been created successfully!.
        /// </summary>
        public static string RoomSuccessfullyCreated {
            get {
                return ResourceManager.GetString("RoomSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ({0}) can&apos;t be registered..
        /// </summary>
        public static string UserFailedRegistration {
            get {
                return ResourceManager.GetString("UserFailedRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid rooms for a particular user (&apos;{0}&apos;) yet.
        /// </summary>
        public static string UserHaveNoRooms {
            get {
                return ResourceManager.GetString("UserHaveNoRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ({0}): Incorrect password..
        /// </summary>
        public static string UserLoginInvalidPassword {
            get {
                return ResourceManager.GetString("UserLoginInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user (id : {0}) can&apos;t get information from this room. Request access from room owner..
        /// </summary>
        public static string UserRoomAccessDenied {
            get {
                return ResourceManager.GetString("UserRoomAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully signed in..
        /// </summary>
        public static string UserSuccessfullLogin {
            get {
                return ResourceManager.GetString("UserSuccessfullLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been successfully registered..
        /// </summary>
        public static string UserSuccessfullRegistration {
            get {
                return ResourceManager.GetString("UserSuccessfullRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User (&apos;{0}&apos;) does not exists..
        /// </summary>
        public static string UserWithNameDoesNotExist {
            get {
                return ResourceManager.GetString("UserWithNameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect room password!.
        /// </summary>
        public static string WrongRoomPassword {
            get {
                return ResourceManager.GetString("WrongRoomPassword", resourceCulture);
            }
        }
    }
}
